- name: Create and Configure a Constructed Inventory in AAP
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Add constructed inventory with two existing input inventories
      ansible.controller.inventory:
        name: "My Constructed Inventory"
        organization: "Default"
        kind: "constructed"
        input_inventories:
          - "Dynamic"
          - "Dynamic-APP-AWS"
        controller_host: http://10.74.131.100
        controller_username: admin
        controller_password: redhat
        validate_certs: false
        state: present
