---
- name: Execute tasks on all nodes
  hosts: all
  tasks:
    - name: Run the command "ls /root" on all nodes
      command: ls /root
      register: ls_output

    - name: Store the command output in a variable using set_facts
      set_fact:
        ping_output: "{{ ls_output.stdout_lines }}"

    - name: Print the variable value
      debug:
        var: ping_output

- name: Use the variable value on localhost
  hosts: localhost
  tasks:
    - name: Pass the variable value to the localhost and store it in another variable
      set_fact:
        new_variable: "{{ hostvars[item]['ping_output'] }}"
      with_items: "{{ groups['all'] }}"
      when: hostvars[item]['ping_output'] is defined

    - name: Print the new variable value
      debug:
        msg: "Combined output: {{ new_variable }}"

